@startuml C4_Code
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Boundary(ctx, "Sistema de Gerenciamento de Tarefas") {
    Component(taskController, "TaskController", "Spring MVC Rest Controller", "Controlador que gerencia as operações CRUD de tarefas via API REST.")
    Component(taskService, "TaskService", "Spring Service", "Serviço que contém a lógica de negócios e chamadas para o repositório de dados.")
    Component(taskRepository, "TaskRepository", "Spring Data Repository", "Repositório que facilita o acesso e a manipulação dos dados de tarefas no banco de dados.")

    Component(task, "Task", "Classe abstrata", "Classe base abstrata para todas as tarefas.")
    Component(dateTask, "DateTask", "Entidade", "Entidade que representa uma tarefa com data específica de conclusão.")
    Component(deadlineTask, "DeadlineTask", "Entidade", "Entidade que representa uma tarefa com prazo em dias.")
    Component(freeTask, "FreeTask", "Entidade", "Entidade que representa uma tarefa livre, sem data ou prazo específico.")

    Rel(taskController, taskService, "Usa")
    Rel(taskService, taskRepository, "Usa")
    Rel(taskRepository, task, "Manipula dados de")
    Rel_U(task, dateTask, "Extende")
    Rel_U(task, deadlineTask, "Extende")
    Rel_U(task, freeTask, "Extende")
}

@enduml